name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

     
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.110.54.3 >> ~/.ssh/known_hosts
       
      - name: Test SSH Connection
        run: ssh -v -i ~/.ssh/id_rsa ubuntu@3.110.54.3 "echo Connected successfully"

      - name: Deploy Code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@3.110.54.3 << 'EOF'
          cd /var/www/html  # Change to your project directory
          git pull origin main
          npm install  # Install dependencies if needed
          pm2 restart all  # Restart process (for Node.js apps)
          EOF
